// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v3.4.0
// source: protos/node.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessUpdatesIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        int64                  `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Deps          []int64                `protobuf:"varint,2,rep,packed,name=deps,proto3" json:"deps,omitempty"`
	Updates       []*Update              `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessUpdatesIn) Reset() {
	*x = ProcessUpdatesIn{}
	mi := &file_protos_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessUpdatesIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUpdatesIn) ProtoMessage() {}

func (x *ProcessUpdatesIn) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUpdatesIn.ProtoReflect.Descriptor instead.
func (*ProcessUpdatesIn) Descriptor() ([]byte, []int) {
	return file_protos_node_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessUpdatesIn) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *ProcessUpdatesIn) GetDeps() []int64 {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *ProcessUpdatesIn) GetUpdates() []*Update {
	if x != nil {
		return x.Updates
	}
	return nil
}

type ProcessUpdatesOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessUpdatesOut) Reset() {
	*x = ProcessUpdatesOut{}
	mi := &file_protos_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessUpdatesOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUpdatesOut) ProtoMessage() {}

func (x *ProcessUpdatesOut) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUpdatesOut.ProtoReflect.Descriptor instead.
func (*ProcessUpdatesOut) Descriptor() ([]byte, []int) {
	return file_protos_node_proto_rawDescGZIP(), []int{1}
}

type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_protos_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_protos_node_proto_rawDescGZIP(), []int{2}
}

func (x *Update) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Update) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_protos_node_proto protoreflect.FileDescriptor

var file_protos_node_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x64,
	0x65, 0x70, 0x73, 0x12, 0x21, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x4f, 0x75, 0x74, 0x22, 0x30, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x3f, 0x0a,
	0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x1a, 0x12, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x4f, 0x75, 0x74, 0x42, 0x09,
	0x5a, 0x07, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_node_proto_rawDescOnce sync.Once
	file_protos_node_proto_rawDescData = file_protos_node_proto_rawDesc
)

func file_protos_node_proto_rawDescGZIP() []byte {
	file_protos_node_proto_rawDescOnce.Do(func() {
		file_protos_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_node_proto_rawDescData)
	})
	return file_protos_node_proto_rawDescData
}

var file_protos_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_node_proto_goTypes = []any{
	(*ProcessUpdatesIn)(nil),  // 0: ProcessUpdatesIn
	(*ProcessUpdatesOut)(nil), // 1: ProcessUpdatesOut
	(*Update)(nil),            // 2: Update
}
var file_protos_node_proto_depIdxs = []int32{
	2, // 0: ProcessUpdatesIn.updates:type_name -> Update
	0, // 1: Node.ProcessUpdates:input_type -> ProcessUpdatesIn
	1, // 2: Node.ProcessUpdates:output_type -> ProcessUpdatesOut
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_node_proto_init() }
func file_protos_node_proto_init() {
	if File_protos_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_node_proto_goTypes,
		DependencyIndexes: file_protos_node_proto_depIdxs,
		MessageInfos:      file_protos_node_proto_msgTypes,
	}.Build()
	File_protos_node_proto = out.File
	file_protos_node_proto_rawDesc = nil
	file_protos_node_proto_goTypes = nil
	file_protos_node_proto_depIdxs = nil
}
